apiVersion: apps/v1
kind: Deployment
metadata:
  name: ioo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ioo
  template:
    metadata:
      labels:
        app: ioo
    spec:
      containers:
      - image: okteto.dev/ioo:latest
        name: ioo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "5ea47329-aef2-4548-8cb8-e3cb1d8ed49f"
        - name: Vless_Path
          value: "/fx65er7rrudmtidu"
        - name: Vmess_UUID
          value: "5ea47329-aef2-4548-8cb8-e3cb1d8ed49f"
        - name: Vmess_Path
          value: "/fdbjdgrshewrs56ehtd"
        - name: Share_Path
          value: "/v2link"
